# Generated by Django 3.2.7 on 2021-09-21 20:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_profession', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skillarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_skill', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_branch', models.CharField(max_length=100)),
                ('skill_level', models.IntegerField(max_length=2)),
                ('area_of_work', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='resume.skillarea')),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('about_me', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('image_main', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('image_sidbar', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('image_about', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('professions', models.ManyToManyField(blank=True, to='resume.Profession')),
            ],
        ),
    ]
