# Generated by Django 3.2.7 on 2021-09-21 20:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_level',
            field=models.IntegerField(default=0, verbose_name=django.core.validators.MaxValueValidator(100)),
        ),
    ]
