# Generated by Django 3.2.7 on 2021-09-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_skill_skill_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_level',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
