# Generated by Django 3.2.7 on 2021-09-22 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_skill_skill_level'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='Aboutme',
        ),
    ]
