# Generated by Django 3.2.7 on 2021-09-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_rename_about_aboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='skill',
            field=models.ManyToManyField(blank=True, to='resume.Skill'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_branch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2),
        ),
    ]
