# Generated by Django 3.2.7 on 2021-09-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20210922_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_level',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3),
        ),
    ]
