# Generated by Django 3.2.7 on 2021-09-23 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_alter_skill_skill_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='area_of_work',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='skillarea',
            field=models.ManyToManyField(blank=True, to='resume.Skillarea'),
        ),
        migrations.AddField(
            model_name='skillarea',
            name='skills',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='resume.skill'),
        ),
    ]
