# Generated by Django 3.2.7 on 2021-09-23 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_auto_20210923_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='skillarea',
        ),
        migrations.RemoveField(
            model_name='skillarea',
            name='skills',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='skill',
            field=models.ManyToManyField(to='resume.Skill'),
        ),
        migrations.AddField(
            model_name='skill',
            name='area_of_work',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.skillarea'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skillarea',
            name='area_skill',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
