# Generated by Django 3.2.7 on 2021-09-23 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_auto_20210923_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='skill',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='skill',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='resume.skill'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
