# Generated by Django 3.2.7 on 2021-09-24 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_auto_20210924_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='email_address',
            field=models.EmailField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='phon_number',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxLengthValidator(12)]),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_level',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
