# Generated by Django 3.2.7 on 2021-09-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_auto_20210924_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='email_address',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
