# Generated by Django 3.2.7 on 2021-09-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_alter_aboutme_phon_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='is_current_job',
            field=models.BooleanField(default=True),
        ),
    ]
