# Generated by Django 3.2.7 on 2021-09-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_experience_is_current_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
    ]
