# Generated by Django 3.2.7 on 2021-09-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0016_alter_portfolio_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
