# Generated by Django 3.2.7 on 2021-09-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0017_auto_20210924_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='social_media_1_icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='social_media_1_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='social_media_1_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='social_media_2_icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='social_media_2_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='social_media_2_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='social_media_3_icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='social_media_3_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='social_media_3_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='social_media_4_icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='social_media_4_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='social_media_4_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='social_media_5_icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='social_media_5_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='social_media_5_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='social_media_6_icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='social_media_6_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='social_media_6_url',
            field=models.URLField(blank=True),
        ),
    ]
