# Generated by Django 3.2.7 on 2021-09-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0019_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_email',
            field=models.EmailField(error_messages={'required': 'Please enter your Email'}, max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_message',
            field=models.TextField(error_messages={'required': 'Please enter your message here'}),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_name',
            field=models.CharField(error_messages={'required': 'Please enter your name'}, max_length=120),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(error_messages={'required': 'Please enter a subject'}, max_length=50),
        ),
    ]
