# Generated by Django 3.2.7 on 2021-10-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0020_auto_20210929_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='upload_cv',
            field=models.FileField(blank=True, upload_to='resume/%Y/%m/%d/'),
        ),
    ]
