# Generated by Django 3.2.7 on 2021-10-02 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0021_aboutme_upload_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='social_media_1_icon',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='social_media_1_name',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='social_media_1_url',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='social_media_2_icon',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='social_media_2_name',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='social_media_2_url',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='social_media_3_icon',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='social_media_3_name',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='social_media_3_url',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='social_media_4_icon',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='social_media_4_name',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='social_media_4_url',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='social_media_5_icon',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='social_media_5_name',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='social_media_5_url',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='social_media_6_icon',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='social_media_6_name',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='social_media_6_url',
        ),
    ]
